### ISSUE TITLE
Bug with 1.4 update

### ISSUE THREAD

**Issue by LucoEldritch** [NotMrFlibble/CustomCollectionsUI#1]
Since there's a new collection (**Rare Pets**), all buttons in Collection Window are pushed down. Because of this, the latest button (**Bugs**) is overlapping (but not covering totally) with the button added by this mod.

Also, I'm not sure if any other changes to Collections happened that could cause this, or if it's another mod (for reference, I'm also using _Lex Legendary Collection_, _Lex Instrument Collection_ and _Geode Reward Collection_, and generally speaking, I have other 35+ mods, **F.U. NOT included**), but when I open any of those extra collections, it closes after 1 second-ish.

(Edit: this second part, it seems like it was reported in this mod's Steam Workshop page, like, 4 months ago... but weirdly, I wasn't having this problem before 1.4)

**Comment by NotMrFlibble** [comment]
Fixed and uploaded.
